# Generated by Django 6.0.6 on 2026-06-15 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeDevis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('company', models.CharField(blank=True, max_length=100)),
                ('project_title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('location', models.CharField(blank=True, max_length=200)),
                ('budget', models.CharField(choices=[('less_500k', 'Moins de 500 000 FCFA'), ('500k_2m', '500 000 — 2 000 000 FCFA'), ('2m_10m', '2 000 000 — 10 000 000 FCFA'), ('more_10m', 'Plus de 10 000 000 FCFA'), ('undefined', 'Budget à définir')], default='undefined', max_length=20)),
                ('urgency', models.CharField(choices=[('asap', 'Urgent (moins de 2 semaines)'), ('month', 'Dans le mois'), ('quarter', 'Dans le trimestre'), ('flexible', 'Flexible')], default='flexible', max_length=20)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='devis_attachments/')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('reviewing', 'En étude'), ('quoted', 'Devis envoyé'), ('accepted', 'Accepté'), ('rejected', 'Refusé')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('domain', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.servicedomain')),
            ],
            options={
                'verbose_name': 'Demande de devis',
                'verbose_name_plural': 'Demandes de devis',
                'ordering': ['-created_at'],
            },
        ),
    ]
