# Generated by Django 6.0.6 on 2026-06-15 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogueCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, default='📦', max_length=10)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Catégorie catalogue',
                'verbose_name_plural': 'Catégories catalogue',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CatalogueItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('service', 'Prestation de service'), ('product', 'Produit / Matériel'), ('pack', 'Pack / Offre groupée')], default='service', max_length=20, verbose_name='Type')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('short_description', models.CharField(max_length=300, verbose_name='Description courte')),
                ('description', models.TextField(verbose_name='Description détaillée')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='catalogue/', verbose_name='Image principale')),
                ('price', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='Prix (FCFA)')),
                ('price_unit', models.CharField(choices=[('unit', 'Unité'), ('m2', 'm²'), ('ml', 'Mètre linéaire'), ('hour', 'Heure'), ('day', 'Jour'), ('forfait', 'Forfait'), ('lot', 'Lot')], default='forfait', max_length=20, verbose_name='Unité de prix')),
                ('price_on_quote', models.BooleanField(default=False, verbose_name='Prix sur devis')),
                ('price_from', models.BooleanField(default=False, verbose_name='À partir de')),
                ('duration', models.CharField(blank=True, max_length=100, verbose_name='Durée / Délai')),
                ('warranty', models.CharField(blank=True, max_length=100, verbose_name='Garantie')),
                ('includes', models.TextField(blank=True, verbose_name='Ce qui est inclus (une ligne = un élément)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Mis en avant')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='boutique.cataloguecategory')),
                ('domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalogue_items', to='core.servicedomain')),
            ],
            options={
                'verbose_name': 'Article catalogue',
                'verbose_name_plural': 'Articles catalogue',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CataloguePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='catalogue/gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='boutique.catalogueitem')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
